"""phase 1 knowledge graph foundation

Revision ID: 0001
Revises:
Create Date: 2026-08-22 22:16:50.871017
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        # pgvector must exist before PostgreSQL parses the VECTOR(384) column.
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("institution", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_locale", sa.String(length=35), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "archived",
                name="course_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "settings_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(code)) > 0", name=op.f("ck_courses_code_not_blank")),
        sa.CheckConstraint("length(trim(title)) > 0", name=op.f("ck_courses_title_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("institution", "code", name="uq_courses_institution_code"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "system_role",
            sa.Enum(
                "user",
                "admin",
                "service",
                name="system_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="user",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "active",
                "suspended",
                "deactivated",
                name="user_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="invited",
            nullable=False,
        ),
        sa.Column("identity_issuer", sa.String(length=500), nullable=True),
        sa.Column("identity_subject", sa.String(length=500), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(identity_issuer IS NULL AND identity_subject IS NULL) OR (identity_issuer IS NOT NULL AND identity_subject IS NOT NULL)",
            name=op.f("ck_users_identity_pair_complete"),
        ),
        sa.CheckConstraint("length(trim(email)) >= 3", name=op.f("ck_users_email_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "identity_issuer", "identity_subject", name="uq_users_identity_issuer_subject"
        ),
    )
    op.create_index("uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True)
    op.create_table(
        "course_memberships",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "student",
                "ta",
                "teacher",
                "admin",
                name="course_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "active",
                "suspended",
                "left",
                name="membership_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="invited",
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'active' OR joined_at IS NOT NULL",
            name=op.f("ck_course_memberships_active_has_joined_at"),
        ),
        sa.CheckConstraint(
            "status <> 'left' OR ended_at IS NOT NULL",
            name=op.f("ck_course_memberships_left_has_ended_at"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_memberships_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_course_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_memberships")),
        sa.UniqueConstraint("course_id", "user_id", name="uq_memberships_course_user"),
    )
    with op.batch_alter_table("course_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_course_memberships_user_status", ["user_id", "status"], unique=False
        )

    op.create_table(
        "curriculum_editions",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("edition_key", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("academic_year", sa.String(length=40), nullable=True),
        sa.Column("term", sa.String(length=80), nullable=True),
        sa.Column("ontology_version", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_review",
                "published",
                "archived",
                name="curriculum_edition_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outline_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_curriculum_editions_published_has_timestamp"),
        ),
        sa.CheckConstraint(
            "length(trim(edition_key)) > 0",
            name=op.f("ck_curriculum_editions_edition_key_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_curriculum_editions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_editions")),
        sa.UniqueConstraint("course_id", "edition_key", name="uq_curriculum_course_edition_key"),
        sa.UniqueConstraint("id", "course_id", name="uq_curriculum_editions_id_course"),
    )
    with op.batch_alter_table("curriculum_editions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_curriculum_editions_course_status", ["course_id", "status"], unique=False
        )

    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_token_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "revoked",
                "expired",
                name="session_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=1000), nullable=True),
        sa.Column("ip_address_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'revoked' OR revoked_at IS NOT NULL",
            name=op.f("ck_user_sessions_revoked_has_timestamp"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_user_sessions_expires_after_creation")
        ),
        sa.CheckConstraint(
            "ip_address_hash IS NULL OR length(ip_address_hash) = 64",
            name=op.f("ck_user_sessions_ip_hash_sha256_length"),
        ),
        sa.CheckConstraint(
            "length(session_token_sha256) = 64",
            name=op.f("ck_user_sessions_token_hash_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint(
            "session_token_sha256", name=op.f("uq_user_sessions_session_token_sha256")
        ),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_sessions_user_status_expires",
            ["user_id", "status", "expires_at"],
            unique=False,
        )

    op.create_table(
        "audit_logs",
        sa.Column(
            "event_type",
            sa.Enum(
                "auth_login",
                "auth_logout",
                "membership_changed",
                "document_ingested",
                "document_quarantined",
                "candidate_reviewed",
                "candidate_edited",
                "candidate_merged",
                "graph_synced",
                "settings_changed",
                name="audit_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "resource_type",
            sa.Enum(
                "user",
                "membership",
                "course",
                "curriculum_edition",
                "document",
                "document_version",
                "node_candidate",
                "relation_candidate",
                "graph_outbox",
                "session",
                name="audit_resource_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_session_id", sa.Uuid(), nullable=True),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "before_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "context_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("previous_event_sha256", sa.String(length=64), nullable=True),
        sa.Column("event_sha256", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_sha256 IS NULL OR length(event_sha256) = 64",
            name=op.f("ck_audit_logs_event_hash_sha256_length"),
        ),
        sa.CheckConstraint(
            "length(trim(summary)) > 0", name=op.f("ck_audit_logs_summary_not_blank")
        ),
        sa.CheckConstraint(
            "previous_event_sha256 IS NULL OR length(previous_event_sha256) = 64",
            name=op.f("ck_audit_logs_previous_hash_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_session_id"],
            ["user_sessions.id"],
            name=op.f("fk_audit_logs_actor_session_id_user_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_audit_logs_course_id_courses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_logs_actor_created", ["actor_user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_audit_logs_course_created", ["course_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_audit_logs_resource", ["resource_type", "resource_id", "created_at"], unique=False
        )

    op.create_table(
        "source_documents",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=True),
        sa.Column("logical_key", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("source_filename", sa.String(length=1000), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "syllabus",
                "lecture_slides",
                "textbook",
                "notes",
                "exercises",
                "solutions",
                "knowledge_export",
                "other",
                name="document_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "authority",
            sa.Enum(
                "course_primary",
                "course_supporting",
                "reference",
                "legacy",
                name="source_authority",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="course_supporting",
            nullable=False,
        ),
        sa.Column(
            "source_role",
            sa.Enum(
                "syllabus",
                "lecture",
                "textbook",
                "notes",
                "exercise",
                "solution",
                "knowledge_export",
                "reference",
                "other",
                name="source_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("authority_priority", sa.Integer(), server_default="50", nullable=False),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "review_required",
                "approved",
                "published",
                "archived",
                "quarantined",
                name="document_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column(
            "bibliographic_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(logical_key)) > 0", name=op.f("ck_source_documents_logical_key_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(source_filename)) > 0", name=op.f("ck_source_documents_filename_not_blank")
        ),
        sa.CheckConstraint(
            "authority_priority >= 0 AND authority_priority <= 100",
            name=op.f("ck_source_documents_authority_priority_range"),
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id", "course_id"],
            ["curriculum_editions.id", "curriculum_editions.course_id"],
            name="fk_source_documents_edition_course",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("course_id", "logical_key", name="uq_documents_course_logical_key"),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_source_documents_authority_priority",
            ["course_id", "authority", "source_role", "authority_priority"],
            unique=False,
        )
        batch_op.create_index(
            "ix_source_documents_course_status", ["course_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_source_documents_edition_type",
            ["curriculum_edition_id", "document_type"],
            unique=False,
        )

    op.create_table(
        "source_document_versions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_file_sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("immutable_source_path", sa.Text(), nullable=False),
        sa.Column("parser_name", sa.String(length=200), nullable=True),
        sa.Column("parser_version", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "review_required",
                "approved",
                "published",
                "archived",
                "failed",
                "superseded",
                name="document_version_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column(
            "parse_diagnostics_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "source_metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("ingested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "byte_size >= 0", name=op.f("ck_source_document_versions_byte_size_nonnegative")
        ),
        sa.CheckConstraint(
            "length(source_file_sha256) = 64",
            name=op.f("ck_source_document_versions_source_hash_sha256_length"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_source_document_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_document_versions_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingested_by_user_id"],
            ["users.id"],
            name=op.f("fk_source_document_versions_ingested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document_versions")),
        sa.UniqueConstraint(
            "document_id", "source_file_sha256", name="uq_document_versions_file_hash"
        ),
        sa.UniqueConstraint("document_id", "version_number", name="uq_document_versions_number"),
    )
    with op.batch_alter_table("source_document_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_versions_status_created", ["status", "created_at"], unique=False
        )

    op.create_table(
        "document_publications",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "published",
                "unpublished",
                "archived",
                name="publication_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="published",
            nullable=False,
        ),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="50", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unpublished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority >= 0 AND priority <= 100",
            name=op.f("ck_document_publications_priority_range"),
        ),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_document_publications_published_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status <> 'unpublished' OR unpublished_at IS NOT NULL",
            name=op.f("ck_document_publications_unpublished_has_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_document_publications_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id"],
            ["curriculum_editions.id"],
            name=op.f("fk_document_publications_curriculum_edition_id_curriculum_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["source_document_versions.id"],
            name=op.f("fk_document_publications_document_version_id_source_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_document_publications_published_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_publications")),
        sa.UniqueConstraint(
            "course_id",
            "document_version_id",
            name="uq_publication_course_version",
        ),
    )
    with op.batch_alter_table("document_publications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_publications_student_lookup",
            ["course_id", "curriculum_edition_id", "status", "priority"],
            unique=False,
        )

    op.create_table(
        "curriculum_outline_sources",
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column(
            "extracted_outline_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id"],
            ["curriculum_editions.id"],
            name=op.f("fk_curriculum_outline_sources_curriculum_edition_id_curriculum_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["source_document_versions.id"],
            name=op.f("fk_curriculum_outline_sources_document_version_id_source_document_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_outline_sources")),
        sa.UniqueConstraint(
            "curriculum_edition_id",
            "document_version_id",
            name="uq_outline_sources_edition_version",
        ),
    )
    with op.batch_alter_table("curriculum_outline_sources", schema=None) as batch_op:
        batch_op.create_index(
            "ix_outline_sources_edition_primary",
            ["curriculum_edition_id", "is_primary"],
            unique=False,
        )

    op.create_table(
        "extraction_runs",
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=200), nullable=False),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("ontology_version", sa.String(length=80), nullable=False),
        sa.Column("model_provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("configuration_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="extraction_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metrics_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status NOT IN ('succeeded', 'failed', 'cancelled') OR completed_at IS NOT NULL",
            name=op.f("ck_extraction_runs_terminal_has_completed_at"),
        ),
        sa.CheckConstraint(
            "length(configuration_sha256) = 64",
            name=op.f("ck_extraction_runs_config_hash_sha256_length"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR completed_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_extraction_runs_completion_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["source_document_versions.id"],
            name=op.f("fk_extraction_runs_document_version_id_source_document_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
    )
    with op.batch_alter_table("extraction_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_extraction_runs_document_status", ["document_version_id", "status"], unique=False
        )

    op.create_table(
        "document_chunks",
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "locator_type",
            sa.Enum(
                "page",
                "slide",
                "paragraph",
                "sheet_row",
                "line",
                "mixed",
                "unlocated",
                name="locator_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("locator_start", sa.String(length=160), nullable=True),
        sa.Column("locator_end", sa.String(length=160), nullable=True),
        sa.Column("physical_page", sa.Integer(), nullable=True),
        sa.Column("printed_page_label", sa.String(length=100), nullable=True),
        sa.Column("slide_number", sa.Integer(), nullable=True),
        sa.Column("paragraph_start", sa.Integer(), nullable=True),
        sa.Column("paragraph_end", sa.Integer(), nullable=True),
        sa.Column(
            "section_path",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "bounding_boxes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("normalized_content", sa.Text(), nullable=True),
        sa.Column("evidence_snippet", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            sa.Text().with_variant(postgresql.TSVECTOR(), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "embedding", sa.JSON().with_variant(Vector(dim=384), "postgresql"), nullable=True
        ),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column("embedding_model", sa.String(length=300), nullable=True),
        sa.Column("extraction_quality", sa.Float(), nullable=True),
        sa.Column(
            "extraction_status",
            sa.Enum(
                "extracted",
                "review_required",
                "ocr_required",
                "approved",
                "rejected",
                name="chunk_extraction_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="extracted",
            nullable=False,
        ),
        sa.Column(
            "parser_metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(embedding IS NULL AND embedding_dimension IS NULL) OR (embedding IS NOT NULL AND embedding_dimension = 384)",
            name=op.f("ck_document_chunks_embedding_fixed_dimension"),
        ),
        sa.CheckConstraint(
            "extraction_quality IS NULL OR (extraction_quality >= 0.0 AND extraction_quality <= 1.0)",
            name=op.f("ck_document_chunks_extraction_quality_unit_interval"),
        ),
        sa.CheckConstraint(
            "length(content) > 0", name=op.f("ck_document_chunks_content_not_empty")
        ),
        sa.CheckConstraint(
            "length(content_sha256) = 64",
            name=op.f("ck_document_chunks_content_hash_sha256_length"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_document_chunks_ordinal_nonnegative")),
        sa.CheckConstraint(
            "paragraph_end IS NULL OR paragraph_end >= 0",
            name=op.f("ck_document_chunks_paragraph_end_nonnegative"),
        ),
        sa.CheckConstraint(
            "paragraph_start IS NULL OR paragraph_end IS NULL OR paragraph_end >= paragraph_start",
            name=op.f("ck_document_chunks_paragraph_range_ordered"),
        ),
        sa.CheckConstraint(
            "paragraph_start IS NULL OR paragraph_start >= 0",
            name=op.f("ck_document_chunks_paragraph_start_nonnegative"),
        ),
        sa.CheckConstraint(
            "physical_page IS NULL OR physical_page > 0",
            name=op.f("ck_document_chunks_physical_page_positive"),
        ),
        sa.CheckConstraint(
            "slide_number IS NULL OR slide_number > 0",
            name=op.f("ck_document_chunks_slide_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["source_document_versions.id"],
            name=op.f("fk_document_chunks_document_version_id_source_document_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_document_chunks_extraction_run_id_extraction_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_version_id", "ordinal", name="uq_chunks_version_ordinal"),
    )
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_chunks_embedding_hnsw",
            ["embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
            postgresql_with={"m": 16, "ef_construction": 64},
        )
        batch_op.create_index(
            "ix_document_chunks_search_vector",
            ["search_vector"],
            unique=False,
            postgresql_using="gin",
        )
        batch_op.create_index(
            "ix_document_chunks_version_locator",
            ["document_version_id", "locator_type", "ordinal"],
            unique=False,
        )

    op.create_table(
        "graph_node_candidates",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "node_type",
            sa.Enum(
                "course",
                "chapter",
                "section",
                "source_document",
                "source_chunk",
                "evidence",
                "concept",
                "principle",
                "physical_system",
                "mathematical_object",
                "operator",
                "quantum_state",
                "approximation",
                "formula",
                "symbol",
                "derivation",
                "example",
                "exercise",
                "misconception",
                "hint",
                "experiment",
                "visualization",
                "project",
                name="graph_node_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("canonical_key", sa.String(length=700), nullable=False),
        sa.Column("label", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("formula_latex", sa.Text(), nullable=True),
        sa.Column(
            "properties_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "llm",
                "rule",
                "imported",
                "manual",
                name="candidate_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "review_required",
                "in_review",
                "approved",
                "rejected",
                "superseded",
                name="candidate_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="review_required",
            nullable=False,
        ),
        sa.Column("revision_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_node_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'superseded' OR superseded_by_node_candidate_id IS NOT NULL",
            name=op.f("ck_graph_node_candidates_superseded_has_successor"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'rejected', 'superseded') OR (reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL)",
            name=op.f("ck_graph_node_candidates_terminal_status_reviewed"),
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_graph_node_candidates_confidence_unit_interval"),
        ),
        sa.CheckConstraint(
            "length(trim(canonical_key)) > 0",
            name=op.f("ck_graph_node_candidates_canonical_key_not_blank"),
        ),
        sa.CheckConstraint(
            "length(trim(label)) > 0", name=op.f("ck_graph_node_candidates_label_not_blank")
        ),
        sa.CheckConstraint(
            "revision_number > 0", name=op.f("ck_graph_node_candidates_revision_number_positive")
        ),
        sa.CheckConstraint(
            "superseded_by_node_candidate_id IS NULL OR superseded_by_node_candidate_id <> id",
            name=op.f("ck_graph_node_candidates_successor_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_graph_node_candidates_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id"],
            ["curriculum_editions.id"],
            name=op.f("fk_graph_node_candidates_curriculum_edition_id_curriculum_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_graph_node_candidates_extraction_run_id_extraction_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_graph_node_candidates_reviewed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f(
                "fk_graph_node_candidates_superseded_by_node_candidate_id_graph_node_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_node_candidates")),
        sa.UniqueConstraint(
            "curriculum_edition_id",
            "node_type",
            "canonical_key",
            "revision_number",
            name="uq_node_candidates_identity_revision",
        ),
    )
    with op.batch_alter_table("graph_node_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_node_candidates_canonical_key",
            ["curriculum_edition_id", "canonical_key"],
            unique=False,
        )
        batch_op.create_index(
            "ix_node_candidates_review_queue",
            ["course_id", "curriculum_edition_id", "status", "node_type"],
            unique=False,
        )

    op.create_table(
        "evidence",
        sa.Column("source_chunk_id", sa.Uuid(), nullable=False),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "text",
                "formula",
                "derivation",
                "figure",
                "table",
                "exercise",
                "claim",
                name="evidence_type",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="text",
            nullable=False,
        ),
        sa.Column("evidence_snippet", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("chunk_content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "grounded",
                "review_required",
                "rejected",
                name="evidence_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="grounded",
            nullable=False,
        ),
        sa.Column(
            "locator_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("char_end > char_start", name=op.f("ck_evidence_char_range_nonempty")),
        sa.CheckConstraint("char_start >= 0", name=op.f("ck_evidence_char_start_nonnegative")),
        sa.CheckConstraint(
            "length(chunk_content_sha256) = 64", name=op.f("ck_evidence_chunk_hash_sha256_length")
        ),
        sa.CheckConstraint(
            "length(evidence_sha256) = 64", name=op.f("ck_evidence_evidence_hash_sha256_length")
        ),
        sa.CheckConstraint(
            "length(trim(evidence_snippet)) > 0", name=op.f("ck_evidence_snippet_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_evidence_source_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint(
            "source_chunk_id",
            "char_start",
            "char_end",
            "evidence_sha256",
            name="uq_evidence_chunk_span_hash",
        ),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_evidence_chunk_status", ["source_chunk_id", "status"], unique=False
        )

    op.create_table(
        "graph_relation_candidates",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_node_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("target_node_candidate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "part_of",
                "prerequisite_of",
                "defines",
                "uses",
                "depends_on",
                "derives_from",
                "applies_to",
                "acts_on",
                "commutes_with",
                "has_eigenstate",
                "approximates",
                "valid_under",
                "contrasts_with",
                "related_to",
                "has_misconception",
                "remediated_by",
                "visualized_by",
                "verified_by",
                "supported_by",
                name="graph_relation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("canonical_key", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "properties_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "llm",
                "rule",
                "imported",
                "manual",
                name="candidate_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "review_required",
                "in_review",
                "approved",
                "rejected",
                "superseded",
                name="candidate_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="review_required",
            nullable=False,
        ),
        sa.Column("revision_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_relation_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'superseded' OR superseded_by_relation_candidate_id IS NOT NULL",
            name=op.f("ck_graph_relation_candidates_superseded_has_successor"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'rejected', 'superseded') OR (reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL)",
            name=op.f("ck_graph_relation_candidates_terminal_status_reviewed"),
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_graph_relation_candidates_confidence_unit_interval"),
        ),
        sa.CheckConstraint(
            "length(trim(canonical_key)) > 0",
            name=op.f("ck_graph_relation_candidates_canonical_key_not_blank"),
        ),
        sa.CheckConstraint(
            "revision_number > 0",
            name=op.f("ck_graph_relation_candidates_revision_number_positive"),
        ),
        sa.CheckConstraint(
            "source_node_candidate_id <> target_node_candidate_id",
            name=op.f("ck_graph_relation_candidates_endpoints_distinct"),
        ),
        sa.CheckConstraint(
            "superseded_by_relation_candidate_id IS NULL OR superseded_by_relation_candidate_id <> id",
            name=op.f("ck_graph_relation_candidates_successor_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_graph_relation_candidates_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id"],
            ["curriculum_editions.id"],
            name=op.f("fk_graph_relation_candidates_curriculum_edition_id_curriculum_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_graph_relation_candidates_extraction_run_id_extraction_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_graph_relation_candidates_reviewed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f(
                "fk_graph_relation_candidates_source_node_candidate_id_graph_node_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f(
                "fk_graph_relation_candidates_superseded_by_relation_candidate_id_graph_relation_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f(
                "fk_graph_relation_candidates_target_node_candidate_id_graph_node_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_relation_candidates")),
        sa.UniqueConstraint(
            "curriculum_edition_id",
            "canonical_key",
            "revision_number",
            name="uq_relation_candidates_identity_revision",
        ),
    )
    with op.batch_alter_table("graph_relation_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_relation_candidates_endpoints",
            ["source_node_candidate_id", "target_node_candidate_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_relation_candidates_review_queue",
            ["course_id", "curriculum_edition_id", "status", "relation_type"],
            unique=False,
        )

    op.create_table(
        "candidate_revisions",
        sa.Column("node_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("relation_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "diff_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("previous_revision_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(node_candidate_id IS NOT NULL AND relation_candidate_id IS NULL) OR (node_candidate_id IS NULL AND relation_candidate_id IS NOT NULL)",
            name=op.f("ck_candidate_revisions_exactly_one_candidate"),
        ),
        sa.CheckConstraint(
            "previous_revision_id IS NULL OR previous_revision_id <> id",
            name=op.f("ck_candidate_revisions_previous_revision_not_self"),
        ),
        sa.CheckConstraint(
            "revision_number > 0", name=op.f("ck_candidate_revisions_revision_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_candidate_revisions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f("fk_candidate_revisions_node_candidate_id_graph_node_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"],
            ["candidate_revisions.id"],
            name=op.f("fk_candidate_revisions_previous_revision_id_candidate_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f("fk_candidate_revisions_relation_candidate_id_graph_relation_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_revisions")),
        sa.UniqueConstraint(
            "node_candidate_id", "revision_number", name="uq_candidate_revisions_node_number"
        ),
        sa.UniqueConstraint(
            "relation_candidate_id",
            "revision_number",
            name="uq_candidate_revisions_relation_number",
        ),
    )
    op.create_table(
        "curriculum_units",
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=False),
        sa.Column("parent_unit_id", sa.Uuid(), nullable=True),
        sa.Column(
            "unit_type",
            sa.Enum(
                "chapter",
                "section",
                "module",
                "topic",
                name="curriculum_unit_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("canonical_path", sa.String(length=1000), nullable=False),
        sa.Column("source_label", sa.String(length=300), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_curriculum_units_title_not_blank")
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_curriculum_units_ordinal_nonnegative")),
        sa.CheckConstraint(
            "parent_unit_id IS NULL OR parent_unit_id <> id",
            name=op.f("ck_curriculum_units_parent_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id"],
            ["curriculum_editions.id"],
            name=op.f("fk_curriculum_units_curriculum_edition_id_curriculum_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_unit_id"],
            ["curriculum_units.id"],
            name=op.f("fk_curriculum_units_parent_unit_id_curriculum_units"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"],
            ["evidence.id"],
            name=op.f("fk_curriculum_units_source_evidence_id_evidence"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_units")),
        sa.UniqueConstraint(
            "curriculum_edition_id", "canonical_path", name="uq_curriculum_units_edition_path"
        ),
    )
    with op.batch_alter_table("curriculum_units", schema=None) as batch_op:
        batch_op.create_index(
            "ix_curriculum_units_parent_ordinal", ["parent_unit_id", "ordinal"], unique=False
        )

    op.create_table(
        "node_candidate_evidence_support",
        sa.Column("node_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "support_role",
            sa.Enum(
                "primary",
                "corroborating",
                "qualifying",
                "contradicting",
                name="evidence_support_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="primary",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "extraction_span_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_node_candidate_evidence_support_confidence_unit_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_node_candidate_evidence_support_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f("fk_node_candidate_evidence_support_node_candidate_id_graph_node_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "node_candidate_id", "evidence_id", name=op.f("pk_node_candidate_evidence_support")
        ),
    )
    with op.batch_alter_table("node_candidate_evidence_support", schema=None) as batch_op:
        batch_op.create_index("ix_node_support_evidence", ["evidence_id"], unique=False)

    op.create_table(
        "relation_candidate_evidence_support",
        sa.Column("relation_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "support_role",
            sa.Enum(
                "primary",
                "corroborating",
                "qualifying",
                "contradicting",
                name="evidence_support_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="primary",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "extraction_span_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_relation_candidate_evidence_support_confidence_unit_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_relation_candidate_evidence_support_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f(
                "fk_relation_candidate_evidence_support_relation_candidate_id_graph_relation_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "relation_candidate_id",
            "evidence_id",
            name=op.f("pk_relation_candidate_evidence_support"),
        ),
    )
    with op.batch_alter_table("relation_candidate_evidence_support", schema=None) as batch_op:
        batch_op.create_index("ix_relation_support_evidence", ["evidence_id"], unique=False)

    op.create_table(
        "review_decisions",
        sa.Column("node_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("relation_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "approve",
                "reject",
                "request_changes",
                "edit",
                "merge",
                name="review_decision_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "before_snapshot_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "after_snapshot_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(node_candidate_id IS NOT NULL AND relation_candidate_id IS NULL) OR (node_candidate_id IS NULL AND relation_candidate_id IS NOT NULL)",
            name=op.f("ck_review_decisions_exactly_one_candidate"),
        ),
        sa.CheckConstraint(
            "length(trim(rationale)) > 0", name=op.f("ck_review_decisions_rationale_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_revision_id"],
            ["candidate_revisions.id"],
            name=op.f("fk_review_decisions_candidate_revision_id_candidate_revisions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f("fk_review_decisions_node_candidate_id_graph_node_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f("fk_review_decisions_relation_candidate_id_graph_relation_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_review_decisions_reviewer_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_decisions_node", ["node_candidate_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_review_decisions_relation", ["relation_candidate_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_review_decisions_reviewer_created", ["reviewer_user_id", "created_at"], unique=False
        )

    op.create_table(
        "candidate_merge_lineage",
        sa.Column("merged_node_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("surviving_node_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("merged_relation_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("surviving_relation_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("review_decision_id", sa.Uuid(), nullable=False),
        sa.Column("merged_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(merged_node_candidate_id IS NOT NULL AND surviving_node_candidate_id IS NOT NULL AND merged_relation_candidate_id IS NULL AND surviving_relation_candidate_id IS NULL) OR (merged_node_candidate_id IS NULL AND surviving_node_candidate_id IS NULL AND merged_relation_candidate_id IS NOT NULL AND surviving_relation_candidate_id IS NOT NULL)",
            name=op.f("ck_candidate_merge_lineage_same_kind_merge_pair"),
        ),
        sa.CheckConstraint(
            "length(trim(rationale)) > 0",
            name=op.f("ck_candidate_merge_lineage_rationale_not_blank"),
        ),
        sa.CheckConstraint(
            "merged_node_candidate_id IS NULL OR merged_node_candidate_id <> surviving_node_candidate_id",
            name=op.f("ck_candidate_merge_lineage_node_merge_distinct"),
        ),
        sa.CheckConstraint(
            "merged_relation_candidate_id IS NULL OR merged_relation_candidate_id <> surviving_relation_candidate_id",
            name=op.f("ck_candidate_merge_lineage_relation_merge_distinct"),
        ),
        sa.ForeignKeyConstraint(
            ["merged_by_user_id"],
            ["users.id"],
            name=op.f("fk_candidate_merge_lineage_merged_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merged_node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f("fk_candidate_merge_lineage_merged_node_candidate_id_graph_node_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merged_relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f(
                "fk_candidate_merge_lineage_merged_relation_candidate_id_graph_relation_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_decision_id"],
            ["review_decisions.id"],
            name=op.f("fk_candidate_merge_lineage_review_decision_id_review_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["surviving_node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f(
                "fk_candidate_merge_lineage_surviving_node_candidate_id_graph_node_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["surviving_relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f(
                "fk_candidate_merge_lineage_surviving_relation_candidate_id_graph_relation_candidates"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_merge_lineage")),
        sa.UniqueConstraint("merged_node_candidate_id", name="uq_merge_lineage_merged_node"),
        sa.UniqueConstraint(
            "merged_relation_candidate_id", name="uq_merge_lineage_merged_relation"
        ),
    )
    op.create_table(
        "graph_sync_outbox",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_edition_id", sa.Uuid(), nullable=False),
        sa.Column("node_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("relation_candidate_id", sa.Uuid(), nullable=True),
        sa.Column(
            "operation",
            sa.Enum(
                "upsert",
                "delete",
                name="graph_sync_operation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("review_decision_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "published",
                "failed",
                "dead_letter",
                name="outbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'processing' OR (locked_at IS NOT NULL AND locked_by IS NOT NULL)",
            name=op.f("ck_graph_sync_outbox_processing_has_lock"),
        ),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_graph_sync_outbox_published_has_timestamp"),
        ),
        sa.CheckConstraint(
            "(node_candidate_id IS NOT NULL AND relation_candidate_id IS NULL) OR (node_candidate_id IS NULL AND relation_candidate_id IS NOT NULL)",
            name=op.f("ck_graph_sync_outbox_exactly_one_candidate"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_graph_sync_outbox_attempt_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_graph_sync_outbox_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_edition_id"],
            ["curriculum_editions.id"],
            name=op.f("fk_graph_sync_outbox_curriculum_edition_id_curriculum_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_candidate_id"],
            ["graph_node_candidates.id"],
            name=op.f("fk_graph_sync_outbox_node_candidate_id_graph_node_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relation_candidate_id"],
            ["graph_relation_candidates.id"],
            name=op.f("fk_graph_sync_outbox_relation_candidate_id_graph_relation_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_decision_id"],
            ["review_decisions.id"],
            name=op.f("fk_graph_sync_outbox_review_decision_id_review_decisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_sync_outbox")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_graph_sync_outbox_idempotency_key")),
    )
    with op.batch_alter_table("graph_sync_outbox", schema=None) as batch_op:
        batch_op.create_index(
            "ix_graph_outbox_dispatch", ["status", "available_at", "created_at"], unique=False
        )

    _install_approval_views(dialect)
    _install_integrity_guards(dialect)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    _remove_integrity_guards(dialect)
    op.execute("DROP VIEW IF EXISTS approved_graph_relations")
    op.execute("DROP VIEW IF EXISTS approved_graph_nodes")
    op.execute("DROP VIEW IF EXISTS student_visible_chunks")
    with op.batch_alter_table("graph_sync_outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_graph_outbox_dispatch")

    op.drop_table("graph_sync_outbox")
    op.drop_table("candidate_merge_lineage")
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_review_decisions_reviewer_created")
        batch_op.drop_index("ix_review_decisions_relation")
        batch_op.drop_index("ix_review_decisions_node")

    op.drop_table("review_decisions")
    with op.batch_alter_table("relation_candidate_evidence_support", schema=None) as batch_op:
        batch_op.drop_index("ix_relation_support_evidence")

    op.drop_table("relation_candidate_evidence_support")
    with op.batch_alter_table("node_candidate_evidence_support", schema=None) as batch_op:
        batch_op.drop_index("ix_node_support_evidence")

    op.drop_table("node_candidate_evidence_support")
    with op.batch_alter_table("curriculum_units", schema=None) as batch_op:
        batch_op.drop_index("ix_curriculum_units_parent_ordinal")

    op.drop_table("curriculum_units")
    op.drop_table("candidate_revisions")
    with op.batch_alter_table("graph_relation_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_relation_candidates_review_queue")
        batch_op.drop_index("ix_relation_candidates_endpoints")

    op.drop_table("graph_relation_candidates")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_chunk_status")

    op.drop_table("evidence")
    with op.batch_alter_table("graph_node_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_node_candidates_review_queue")
        batch_op.drop_index("ix_node_candidates_canonical_key")

    op.drop_table("graph_node_candidates")
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_document_chunks_version_locator")
        batch_op.drop_index("ix_document_chunks_search_vector", postgresql_using="gin")
        batch_op.drop_index(
            "ix_document_chunks_embedding_hnsw",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
            postgresql_with={"m": 16, "ef_construction": 64},
        )

    op.drop_table("document_chunks")
    with op.batch_alter_table("extraction_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_extraction_runs_document_status")

    op.drop_table("extraction_runs")
    with op.batch_alter_table("curriculum_outline_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_outline_sources_edition_primary")

    op.drop_table("curriculum_outline_sources")
    with op.batch_alter_table("document_publications", schema=None) as batch_op:
        batch_op.drop_index("ix_document_publications_student_lookup")

    op.drop_table("document_publications")
    with op.batch_alter_table("source_document_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_document_versions_status_created")

    op.drop_table("source_document_versions")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_source_documents_authority_priority")
        batch_op.drop_index("ix_source_documents_edition_type")
        batch_op.drop_index("ix_source_documents_course_status")

    op.drop_table("source_documents")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_resource")
        batch_op.drop_index("ix_audit_logs_course_created")
        batch_op.drop_index("ix_audit_logs_actor_created")

    op.drop_table("audit_logs")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_user_sessions_user_status_expires")

    op.drop_table("user_sessions")
    with op.batch_alter_table("curriculum_editions", schema=None) as batch_op:
        batch_op.drop_index("ix_curriculum_editions_course_status")

    op.drop_table("curriculum_editions")
    with op.batch_alter_table("course_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_course_memberships_user_status")

    op.drop_table("course_memberships")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("courses")
    # ### end Alembic commands ###


def _install_approval_views(dialect: str) -> None:
    """Expose a deliberately narrow, approval-only graph projection."""

    op.execute(
        """
        CREATE VIEW student_visible_chunks AS
        SELECT
            chunk.*,
            document.course_id,
            publication.curriculum_edition_id AS publication_curriculum_edition_id,
            document.id AS source_document_id,
            document.title AS source_document_title,
            document.source_filename,
            document.authority,
            document.source_role,
            document.authority_priority,
            publication.priority AS publication_priority,
            publication.published_at
        FROM document_chunks AS chunk
        JOIN source_document_versions AS version
          ON version.id = chunk.document_version_id
         AND version.status = 'published'
        JOIN source_documents AS document
          ON document.id = version.document_id
         AND document.status = 'published'
        JOIN document_publications AS publication
          ON publication.document_version_id = version.id
         AND publication.course_id = document.course_id
         AND publication.status = 'published'
         AND (
              document.curriculum_edition_id IS NULL
              OR document.curriculum_edition_id = publication.curriculum_edition_id
         )
        WHERE chunk.extraction_status = 'approved'
        """
    )
    op.execute(
        """
        CREATE VIEW approved_graph_nodes AS
        SELECT
            id,
            course_id,
            curriculum_edition_id,
            node_type,
            canonical_key,
            label,
            description,
            formula_latex,
            properties_json,
            revision_number,
            reviewed_by_user_id,
            reviewed_at
        FROM graph_node_candidates
        WHERE status = 'approved'
        """
    )
    op.execute(
        """
        CREATE VIEW approved_graph_relations AS
        SELECT
            relation.id,
            relation.course_id,
            relation.curriculum_edition_id,
            relation.source_node_candidate_id,
            relation.target_node_candidate_id,
            relation.relation_type,
            relation.canonical_key,
            relation.description,
            relation.properties_json,
            relation.revision_number,
            relation.reviewed_by_user_id,
            relation.reviewed_at
        FROM graph_relation_candidates AS relation
        JOIN graph_node_candidates AS source_node
          ON source_node.id = relation.source_node_candidate_id
         AND source_node.status = 'approved'
        JOIN graph_node_candidates AS target_node
          ON target_node.id = relation.target_node_candidate_id
         AND target_node.status = 'approved'
        WHERE relation.status = 'approved'
        """
    )


def _install_integrity_guards(dialect: str) -> None:
    if dialect == "postgresql":
        _install_postgresql_guards()
    elif dialect == "sqlite":
        _install_sqlite_guards()


def _install_postgresql_guards() -> None:
    # File identity defines a source version and is immutable after insertion.
    op.execute(
        """
        CREATE FUNCTION qa_reject_source_version_identity_update()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.document_id IS DISTINCT FROM OLD.document_id
             OR NEW.version_number IS DISTINCT FROM OLD.version_number
             OR NEW.source_file_sha256 IS DISTINCT FROM OLD.source_file_sha256
             OR NEW.immutable_source_path IS DISTINCT FROM OLD.immutable_source_path THEN
            RAISE EXCEPTION 'source document version identity is immutable';
          END IF;
          RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_source_version_identity_immutable
        BEFORE UPDATE ON source_document_versions
        FOR EACH ROW EXECUTE FUNCTION qa_reject_source_version_identity_update()
        """
    )

    # Audit rows are append-only even if application code is compromised.
    op.execute(
        """
        CREATE FUNCTION qa_reject_audit_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'audit logs are append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION qa_reject_audit_mutation()
        """
    )

    # `search_text` is pre-tokenized by ingestion (including jieba terms); the
    # simple configuration preserves symbols and avoids English-only stemming.
    op.execute(
        """
        CREATE FUNCTION qa_document_chunks_search_vector_update()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          NEW.search_vector := to_tsvector('simple', COALESCE(NEW.search_text, ''));
          RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_document_chunks_search_vector
        BEFORE INSERT OR UPDATE OF search_text ON document_chunks
        FOR EACH ROW EXECUTE FUNCTION qa_document_chunks_search_vector_update()
        """
    )

    # Neo4j UPSERT events are accepted only when a matching teacher approval
    # exists, and relations additionally require two approved endpoints.
    op.execute(
        """
        CREATE FUNCTION qa_guard_graph_sync_outbox()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.operation = 'upsert' THEN
            IF NEW.node_candidate_id IS NOT NULL THEN
              PERFORM 1
              FROM graph_node_candidates AS candidate
              JOIN review_decisions AS decision
                ON decision.id = NEW.review_decision_id
               AND decision.node_candidate_id = candidate.id
               AND decision.decision = 'approve'
              WHERE candidate.id = NEW.node_candidate_id
                AND candidate.course_id = NEW.course_id
                AND candidate.curriculum_edition_id = NEW.curriculum_edition_id
                AND candidate.status = 'approved';
            ELSE
              PERFORM 1
              FROM graph_relation_candidates AS candidate
              JOIN graph_node_candidates AS source_node
                ON source_node.id = candidate.source_node_candidate_id
               AND source_node.status = 'approved'
              JOIN graph_node_candidates AS target_node
                ON target_node.id = candidate.target_node_candidate_id
               AND target_node.status = 'approved'
              JOIN review_decisions AS decision
                ON decision.id = NEW.review_decision_id
               AND decision.relation_candidate_id = candidate.id
               AND decision.decision = 'approve'
              WHERE candidate.id = NEW.relation_candidate_id
                AND candidate.course_id = NEW.course_id
                AND candidate.curriculum_edition_id = NEW.curriculum_edition_id
                AND candidate.status = 'approved';
            END IF;

            IF NOT FOUND THEN
              RAISE EXCEPTION 'Neo4j upsert requires approved, in-scope knowledge';
            END IF;
          END IF;
          RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_graph_sync_outbox_approved_only
        BEFORE INSERT OR UPDATE OF operation, node_candidate_id,
          relation_candidate_id, review_decision_id, course_id,
          curriculum_edition_id
        ON graph_sync_outbox
        FOR EACH ROW EXECUTE FUNCTION qa_guard_graph_sync_outbox()
        """
    )


def _install_sqlite_guards() -> None:
    op.execute(
        """
        CREATE TRIGGER trg_source_version_identity_immutable
        BEFORE UPDATE OF document_id, version_number, source_file_sha256,
          immutable_source_path ON source_document_versions
        WHEN NEW.document_id <> OLD.document_id
          OR NEW.version_number <> OLD.version_number
          OR NEW.source_file_sha256 <> OLD.source_file_sha256
          OR NEW.immutable_source_path <> OLD.immutable_source_path
        BEGIN
          SELECT RAISE(ABORT, 'source document version identity is immutable');
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_logs_no_update
        BEFORE UPDATE ON audit_logs
        BEGIN
          SELECT RAISE(ABORT, 'audit logs are append-only');
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_logs_no_delete
        BEFORE DELETE ON audit_logs
        BEGIN
          SELECT RAISE(ABORT, 'audit logs are append-only');
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_document_chunks_search_vector_insert
        AFTER INSERT ON document_chunks
        BEGIN
          UPDATE document_chunks SET search_vector = NEW.search_text WHERE id = NEW.id;
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_document_chunks_search_vector_update
        AFTER UPDATE OF search_text ON document_chunks
        BEGIN
          UPDATE document_chunks SET search_vector = NEW.search_text WHERE id = NEW.id;
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_graph_sync_outbox_approved_only
        BEFORE INSERT ON graph_sync_outbox
        WHEN NEW.operation = 'upsert' AND NOT (
          (
            NEW.node_candidate_id IS NOT NULL
            AND EXISTS (
              SELECT 1
              FROM graph_node_candidates AS candidate
              JOIN review_decisions AS decision
                ON decision.id = NEW.review_decision_id
               AND decision.node_candidate_id = candidate.id
               AND decision.decision = 'approve'
              WHERE candidate.id = NEW.node_candidate_id
                AND candidate.course_id = NEW.course_id
                AND candidate.curriculum_edition_id = NEW.curriculum_edition_id
                AND candidate.status = 'approved'
            )
          ) OR (
            NEW.relation_candidate_id IS NOT NULL
            AND EXISTS (
              SELECT 1
              FROM graph_relation_candidates AS candidate
              JOIN graph_node_candidates AS source_node
                ON source_node.id = candidate.source_node_candidate_id
               AND source_node.status = 'approved'
              JOIN graph_node_candidates AS target_node
                ON target_node.id = candidate.target_node_candidate_id
               AND target_node.status = 'approved'
              JOIN review_decisions AS decision
                ON decision.id = NEW.review_decision_id
               AND decision.relation_candidate_id = candidate.id
               AND decision.decision = 'approve'
              WHERE candidate.id = NEW.relation_candidate_id
                AND candidate.course_id = NEW.course_id
                AND candidate.curriculum_edition_id = NEW.curriculum_edition_id
                AND candidate.status = 'approved'
            )
          )
        )
        BEGIN
          SELECT RAISE(ABORT, 'Neo4j upsert requires approved, in-scope knowledge');
        END
        """
    )


def _remove_integrity_guards(dialect: str) -> None:
    if dialect == "postgresql":
        op.execute(
            "DROP TRIGGER IF EXISTS trg_graph_sync_outbox_approved_only ON graph_sync_outbox"
        )
        op.execute("DROP FUNCTION IF EXISTS qa_guard_graph_sync_outbox()")
        op.execute("DROP TRIGGER IF EXISTS trg_document_chunks_search_vector ON document_chunks")
        op.execute("DROP FUNCTION IF EXISTS qa_document_chunks_search_vector_update()")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS qa_reject_audit_mutation()")
        op.execute(
            "DROP TRIGGER IF EXISTS trg_source_version_identity_immutable "
            "ON source_document_versions"
        )
        op.execute("DROP FUNCTION IF EXISTS qa_reject_source_version_identity_update()")
    elif dialect == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS trg_graph_sync_outbox_approved_only")
        op.execute("DROP TRIGGER IF EXISTS trg_document_chunks_search_vector_update")
        op.execute("DROP TRIGGER IF EXISTS trg_document_chunks_search_vector_insert")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_delete")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_update")
        op.execute("DROP TRIGGER IF EXISTS trg_source_version_identity_immutable")
